Header 추가했습니다.
DSM-DMS/DMS-Front-V4 pull request #11
Opened 2019-08-30 04:48 UTC by leafcis

2019-08-30 04:55 UTC, wArrnp requested changes

2019-08-30 04:55 UTC, gtobio11 commented on src/components/Common/Header.tsx
> +const Header : React.FC<HeaderProps> = () => {
Component에서 UI 관련 State를 사용하지 않는다면 FC 말고 Stateless를 사용하는 것이 좋을 것 같습니다.

2019-08-31 09:45 UTC, leafcis commented on src/components/Common/Header.tsx
> +const Header : React.FC<HeaderProps> = () => {
알겠습니다.

2019-08-31 10:44 UTC, leafcis reviewed
수정 완료

2019-08-31 12:41 UTC, gtobio11 commented
추후에 스크롤 관련 event 처리 부탁드리겠습니다.

2019-08-31 12:41 UTC, merged