Apply 잔류 신청 파트 완료
DSM-DMS/DMS-Front-V4 pull request #12
Opened 2019-08-31 10:42 UTC by leafcis

아이콘은 리소스가 아직 없습니다.

2019-08-31 12:48 UTC, wArrnp requested changes

2019-08-31 12:48 UTC, gtobio11 commented on src/containers/Apply/Apply.tsx
> +        <Apply state = {apply}/>
state 보다 좀 더 명시적인 변수 명이 좋을 것 같습니다. apply의 현재 view라는 점을 좀 더 명시적으로 표현해주세요.

2019-08-31 12:48 UTC, gtobio11 commented on src/containers/ApplyStay/ApplyStay.tsx
> +            <ApplyStayButton data = {data} key = {data.kind}/>
data = {data}보다는 {...data}로 구조 분해를 해주는 것이 더 좋을 것 같습니다.

2019-08-31 13:12 UTC, leafcis commented on src/containers/Apply/Apply.tsx
> +        <Apply state = {apply}/>
변경했습니다.

2019-08-31 13:12 UTC, leafcis commented on src/containers/ApplyStay/ApplyStay.tsx
> +            <ApplyStayButton data = {data} key = {data.kind}/>
변경했습니다.

2019-08-31 13:55 UTC, khg0712 requested changes

2019-08-31 13:55 UTC, khg0712 commented on src/components/Apply/Apply.tsx
> +    let ApplySection = <ApplyStayContainer />;
초기화를 해주는 이유가 뭔가요?

2019-08-31 13:55 UTC, khg0712 commented on src/components/ApplyStay/ApplyStay.tsx
> +interface ApplyStayProps {
탭의 여백 개수가 맞지 않는 것 같은데 2개로 통일하는 게 좋을 것 같습니다.

2019-08-31 13:55 UTC, khg0712 commented on src/components/index.js
> +>>>>>>> 7155fe4febde0c7caef30f657bdb7980de715b4f
의미없는 코드는 지워주세요

2019-08-31 13:55 UTC, khg0712 commented on src/components/index.js
> +<<<<<<< HEAD
conflict가 제대로 해결되지 않은 것 같습니다.

2019-08-31 13:55 UTC, khg0712 commented on src/containers/ApplyStay/ApplyStay.tsx
> +            gohome_time : '금요일 20시 30분~ 21시 00분 귀가',
음절의 단위로 끊으면 `go_home_time` 이 옳은 것 아닌가요?

2019-08-31 13:57 UTC, leafcis commented on src/components/ApplyStay/ApplyStay.tsx
> +interface ApplyStayProps {
넵 알겠습니다.

2019-08-31 14:06 UTC, gtobio11 commented on src/components/Apply/Apply.tsx
> +    let ApplySection = <ApplyStayContainer />;
useState, useEffect를 써주는 것도 좋을 것 같다고 생각합니다 ~

2019-09-05 06:25 UTC, khg0712 approved these changes

2019-09-06 00:45 UTC, wArrnp approved these changes

2019-09-06 05:14 UTC, gimtommang11 approved these changes

2019-09-08 14:17 UTC, merged