[ADD] login modal 퍼블리싱 완성
DSM-DMS/DMS-Front-V4 pull request #14
Opened 2019-09-02 13:42 UTC by gimtommang11

2019-09-03 05:12 UTC, wArrnp requested changes

2019-09-03 05:12 UTC, gtobio11 commented on src/components/modals/Login.tsx
> +      <S.ModalBottomWrepper>
wrepper 오타인 것 같네요. wrapper로 수정해주세요.

2019-09-03 05:12 UTC, gtobio11 commented on src/components/modals/Login.tsx
> +        </S.ModalBottomWrepper>
이부분 띄어쓰기 갯수가 틀린거 같은데 확인 부탁드립니다.

2019-09-03 05:12 UTC, gtobio11 commented on src/components/modals/modal.tsx
> +    <div>
이 div는 꼭 있어야할 필요가 있나요 ? 질문입니다.

2019-09-03 05:13 UTC, gtobio11 commented
Login 같은 경우에 ModalLogin과 같이 새로운 폴더를 생성해서 해주는 것이 좋을 것 같습니다 ㅎㅎ 저희 지금 프로젝트 폴더 구조가 그런 방향으로 잡혀있어서 통일성을 위해서 수정 부탁드리겠습니다 ~

2019-09-03 05:16 UTC, wArrnp requested changes

2019-09-03 05:16 UTC, gtobio11 commented on src/components/modals/Login.tsx
> +    <div>
외부에서 ModalContainer로 감싸주는 것 같은데, div가 꼭 필요하지 않은 상황이라면 Fragment를 사용하면 좋을 것 같습니다. (<></>) 불필요한 dom depth는 줄이는 것이 좋아요 !!

2019-09-03 05:16 UTC, gtobio11 commented on src/components/modals/style.ts
> +export const Modal_overlay = styled.div`
변수의 이름이 저희 변수 네이밍 컨벤션에 적절하지 못합니다. ModalOverlay로 수정해주세요.

2019-09-03 05:16 UTC, gtobio11 commented on src/components/modals/style.ts
> +export const ModalContnetWrapper = styled.div`
Content를 쓰고자 했던 것 같은데 오타같습니다. 수정해주세요.

2019-09-03 05:18 UTC, gtobio11 commented on src/components/modals/style.ts
> +export const Modal_overlay = styled.div`
또한 이 변수 ? 가 사용되는 곳이 보이지 않는데 확인 부탁드립니다 !

2019-09-03 05:19 UTC, gtobio11 commented
그리구 commit rule 에서 []까지는 잘했는데 <>가 빠진 것 같아요 ㅠㅠ 이건 어쩔 수 없지만 수정 혹은 다음 commit 부터는 주의 부탁드립니다.

2019-09-04 13:37 UTC, gimtommang11 commented on src/components/modals/Login.tsx
> +      <S.ModalBottomWrepper>
넵 수정하였습니다

2019-09-04 13:39 UTC, gimtommang11 commented on src/components/modals/Login.tsx
> +        </S.ModalBottomWrepper>
아직 DMS 회원이 아니시라면? 부분은 띄어쓰기 개수 디자인과 일치합니당

2019-09-04 14:31 UTC, gimtommang11 commented on src/components/modals/Login.tsx
> +    <div>
넵 수정하겠습니다 !!

2019-09-04 15:46 UTC, gimtommang11 commented on src/components/modals/style.ts
> +export const Modal_overlay = styled.div`
변수명 수정하였고 변수 원래 modal.tsx 에 사용되었는데 지워버린 것 같습니다. 다시 추가하였습니다

2019-09-04 15:47 UTC, gimtommang11 commented on src/components/modals/style.ts
> +export const ModalContnetWrapper = styled.div`
넵 수정하였습니다

2019-09-04 15:54 UTC, gimtommang11 commented on src/components/modals/modal.tsx
> +    <div>
원래 modal overlay 엘리먼트를 포함하고 있었기 때문에 썼는데 삭제해서 필요없어진것같네요/ modal overlay 추가 후 fragment로 추가하도록 하겠습니다! :)

2019-09-05 02:18 UTC, wArrnp approved these changes
확인 했습니다. 저는 머지해도 괜찮다고 생각하고 다른 친구들 pr 부탁드린다고 말씀해주세요 !! ㅎㅎㅎ 수고하셨습니당

2019-09-05 06:11 UTC, khg0712 requested changes

2019-09-05 06:11 UTC, khg0712 commented on src/components/modals/Login.tsx
> +
의미 없는 공백 지워주세요

2019-09-05 06:11 UTC, khg0712 commented on src/components/modals/Login.tsx
> +  )
세미콜론을 찍는 게 더 좋아보여요

2019-09-05 06:11 UTC, khg0712 commented on src/components/modals/modal.tsx
> +
의미없는 공백입니다

2019-09-05 06:11 UTC, khg0712 commented on src/components/modals/modal.tsx
> +  )
세미콜론이 필요해보입니다.

2019-09-05 06:11 UTC, khg0712 commented on src/components/modals/style.ts
> +
의미없는 공백

2019-09-05 06:11 UTC, khg0712 commented on src/components/modals/style.ts
> +
공백

2019-09-05 06:11 UTC, khg0712 commented on src/components/modals/style.ts
> +  {/*width: 24.75rem;  */}
왜 주석이 남아있는 건가요?

2019-09-05 06:11 UTC, khg0712 commented on src/components/modals/style.ts
> +
공백입니다

2019-09-05 06:11 UTC, khg0712 commented on src/components/modals/style.ts
> +
공백

2019-09-05 06:16 UTC, gimtommang11 commented on src/components/modals/style.ts
> +  {/*width: 24.75rem;  */}
주석 삭제하였습니다

2019-09-05 23:43 UTC, leafcis approved these changes

2019-09-09 05:08 UTC, khg0712 approved these changes

2019-09-09 05:09 UTC, khg0712 commented
커멘트에 달린 리뷰의 내용이 해결이 되었다면 resolve로 해결됐음을 알려주세요 @gimtommang11

2019-09-09 08:32 UTC, merged