Sign in 퍼블리싱 완료
DSM-DMS/DMS-Front-V4 pull request #15
Opened 2019-09-16 10:29 UTC by gimtommang11

2019-09-16 14:05 UTC, wArrnp requested changes
컴포넌트 명과 파일명은 SignIn인데 내부 스타일로써 만들어진 컴포넌트는 Signin으로 i 와 I의 차이가 있는데 되도록 맞춰주세요.

2019-09-16 14:05 UTC, gtobio11 commented on src/components/modals/style.ts
> +  {/*height: 10.5rem;*/}
필요없는 주석이라면 지워주세요 .

2019-09-16 14:05 UTC, gtobio11 commented on src/components/modals/style.ts
> +  {/*margin-bottom:1rem;*/}
필요없는 주석이라면 지워주세요

2019-09-16 14:05 UTC, gtobio11 commented on src/components/modals/style.ts
> +  font-size:s  0.875rem;
s는 왜 있는건가요 ?

2019-09-16 14:07 UTC, wArrnp requested changes

2019-09-16 14:07 UTC, gtobio11 commented on src/components/Modals/SignIn.tsx
> +const SignIn: React.FC<Props> =()=> {
상태가 없는 컴포넌트이면 stateless component 사용해주세요.

2019-09-16 14:09 UTC, wArrnp requested changes

2019-09-16 14:09 UTC, gtobio11 commented on src/components/Modals/SignIn.tsx
> +      <S.button>회원가입</S.button>
이 스타일 컴포넌트의 이름은 왜 대문자로 시작하지 않나요 ?

2019-09-16 14:09 UTC, gtobio11 commented on src/components/Modals/SignIn.tsx
> +      <S.button>회원가입</S.button>
모달에서 사용되는 버튼이라는 의미를 좀 더 담아주었으면 좋겠습니다.

2019-09-18 14:35 UTC, gimtommang11 commented on src/components/modals/style.ts
> +  {/*height: 10.5rem;*/}
넵

2019-09-18 14:38 UTC, gimtommang11 commented on src/components/modals/style.ts
> +  {/*margin-bottom:1rem;*/}
넵

2019-09-18 14:38 UTC, gimtommang11 commented on src/components/modals/style.ts
> +  font-size:s  0.875rem;
오타났나봐요 삭제하겠습니다 ㅠㅠ

2019-09-18 14:39 UTC, gimtommang11 commented on src/components/Modals/SignIn.tsx
> +      <S.button>회원가입</S.button>
넵 수정하겠습니다

2019-09-18 14:40 UTC, gimtommang11 commented on src/components/Modals/SignIn.tsx
> +const SignIn: React.FC<Props> =()=> {
넵 수정하도록 하겠습니다

2019-09-29 13:52 UTC, wArrnp requested changes

2019-09-29 13:52 UTC, gtobio11 commented on src/components/Modals/SignIn.tsx
> +const SignIn: React.SFC<Props> =()=> {
SFC 는 더이상 지원되지 않습니다. StatelessComponent로 수정해주세요.

2019-09-30 10:59 UTC, merged