Chatting
DSM-DMS/DMS-Front-V4 pull request #25
Opened 2019-09-20 07:17 UTC by gtobio11

2019-09-22 15:53 UTC, gimtommang11 approved these changes

2019-09-25 14:06 UTC, khg0712 requested changes

2019-09-25 14:06 UTC, khg0712 commented on src/components/Chatting/Chatting.tsx
> +  setIsChatOpen: (isChatOpen: boolean) => void;
```suggestion
  openChat: (isChatOpened: boolean) => void;
```
이게 더 좋아보이네요

2019-09-25 14:06 UTC, khg0712 commented on src/components/SideBar/SideBar.tsx
> +  setChattingToggle: () => void;
위에서는 Chat, 여기서는 Chatting, 단어 통일의 필요성이 느껴집니다.

2019-09-25 14:06 UTC, khg0712 commented on src/modules/chat.ts
> +  type: SET_IS_SELECTED_OPEN,
type이 이름과 다른 이유가 있나요?

2019-09-26 05:07 UTC, gimtommang11 approved these changes

2019-09-26 14:45 UTC, gtobio11 commented on src/components/SideBar/SideBar.tsx
> +  setChattingToggle: () => void;
해결했습니다.

2019-09-26 14:46 UTC, gtobio11 commented on src/components/Chatting/Chatting.tsx
> +  setIsChatOpen: (isChatOpen: boolean) => void;
isChatOpened의 값을 수정한다는 의미로 setIsChatOpened가 더 명시적일것 같고, 저 함수자체가 Open만 하지 않기때문에 setIsChatOpened로 수정하겠습니다.

2019-09-26 14:46 UTC, gtobio11 commented on src/modules/chat.ts
> +  type: SET_IS_SELECTED_OPEN,
코드 수정 중 오류 인것 같습니다. 수정했습니다.

2019-09-29 13:50 UTC, merged