Bug report 모달 퍼블리싱 완성
DSM-DMS/DMS-Front-V4 pull request #28
Opened 2019-09-25 13:51 UTC by gimtommang11

2019-09-25 14:13 UTC, khg0712 requested changes

2019-09-25 14:13 UTC, khg0712 commented on src/components/Modals/SignIn.tsx
> +const SignIn: React.SFC<Props> =()=> {
```suggestion
const SignIn: React.FC<Props> =()=> {
```
react SFC는 개발 중지됐습니다. FC로 사용하세요

2019-09-25 14:13 UTC, khg0712 commented on src/components/Modals/SignIn.tsx
> +
공백 지워주세용

2019-09-25 14:13 UTC, khg0712 commented on src/components/modals/BugReport.tsx
> +import ModalCloseImg from '../../assets/icon/black-close-button.png';
간단하게 closeImg로 사용해도 될 것 같습니다. => 간단한 제안입니다. 굳이 따르지 않으셔도 됩니다 ㅎㅎ

2019-09-25 14:13 UTC, khg0712 commented on src/components/modals/BugReport.tsx
> +const BugReport: React.SFC<Props>=()=>{
FC로 사용해주세요

2019-09-26 05:07 UTC, gimtommang11 commented on src/components/Modals/SignIn.tsx
> +const SignIn: React.SFC<Props> =()=> {
넵

2019-09-27 00:00 UTC, gtobio11 commented on src/components/Modals/SignIn.tsx
> +const SignIn: React.SFC<Props> =()=> {
Stateless로 사용하고싶다면 StatelessComponent도 있습니다.

2019-09-29 13:55 UTC, wArrnp approved these changes

2019-10-07 11:17 UTC, merged