Log in 퍼블리싱 수정, 완료
DSM-DMS/DMS-Front-V4 pull request #29
Opened 2019-09-26 00:48 UTC by gimtommang11

변경된 디자인에 맞춰서 수정하였습니다

2019-09-27 03:12 UTC, khg0712 commented on src/components/modals/modal.tsx
> +
공백 지워주세오

2019-09-29 13:57 UTC, wArrnp requested changes

2019-09-29 13:57 UTC, gtobio11 commented on src/components/Modals/SignIn.tsx
> +const SignIn: React.FC<Props> =()=> {
내부 상태가 확인되지 않는 것을 보아 StatelessComponent로 사용하는 것이 더 좋을 것 같습니다.

2019-09-29 13:57 UTC, gtobio11 commented on src/components/modals/BugReport.tsx
> +const BugReport: React.FC<Props>=()=>{
내부 상태가 확인되지 않는 것을 보아 StatelessComponent로 사용하는 것이 더 좋을 것 같습니다.

2019-09-29 13:57 UTC, gtobio11 commented on src/components/modals/Login.tsx
> +const LogIn: React.FC<Props> = () => {
내부 상태가 확인되지 않는 것을 보아 StatelessComponent로 사용하는 것이 더 좋을 것 같습니다.

2019-10-17 05:07 UTC, merged