Meal publishing 완성
DSM-DMS/DMS-Front-V4 pull request #35
Opened 2019-12-10 03:32 UTC by gimtommang11

Main 급식부분 퍼블리싱 완성하였습니다.

2019-12-10 13:32 UTC, khg0712 requested changes

2019-12-10 13:32 UTC, khg0712 commented on src/components/MealCard/MealCard.tsx
> +      <S.MealCardContainer>
이거 급식 메뉴 길이랑 메뉴 개수에 따라서 스타일을 다르게 해야될 것 같은데 고려해주세요~

2019-12-10 13:32 UTC, khg0712 commented on src/components/MealInfo/MealInfo.tsx
> +const MealInfo: React.StatelessComponent<Props> = ({ mealInfo }) => {
`React.StatelessComponent` deprecated 됐어요 ㅜㅜ `React.FC` 사용해주세요~~

2019-12-11 05:24 UTC, wArrnp requested changes
Container 묶어주셔서 export한 후 import하는 것은 필수로 진행해주시구요.
나머지는 참고해주셔서 수정 부탁드립니다.

2019-12-11 05:24 UTC, gtobio11 commented on src/Routing.tsx
> +import MealContainer from './containers/Meal/Meal';
위와 같이 containers/index.js에서 파일을 하나로 모아주신 후 export 시켜주세요.

그 후 위의 Notice와 Mypage, Apply container import한 것처럼 묶어주시면 됩니다.

2019-12-11 05:24 UTC, gtobio11 commented on src/components/Meal/Meal.tsx
> +    <>
여기서 굳이 fragment를 사용할 이유는 없을 것 같네요.

2019-12-11 05:24 UTC, gtobio11 commented on src/components/MealCard/MealCard.tsx
> +  eatingTime: String;
String -> string

2019-12-11 05:24 UTC, gtobio11 commented on src/components/MealCard/MealCard.tsx
> +    <>
이곳 또한 Fragment의 존재 이유가 없습니다.

2019-12-11 05:24 UTC, gtobio11 commented on src/components/MealCard/style.ts
> +`;
이건 의견이지만, margin은 margin들 끼리 폰트 관련은 폰트 관련들끼리 모아주는 것이 코드 가독성에 좋지 않을까 합니다.

2019-12-11 05:24 UTC, gtobio11 commented on src/containers/Meal/Meal.tsx
> +  const mealList = {
차후에 useState를 통해 바꿔주실꺼라 생각합니다 ~

2019-12-11 05:24 UTC, gtobio11 commented on src/containers/Meal/Meal.tsx
> +    <>
Fragment없어도 됩니다 ! 있을 이유가 없어요 ㅠㅠ

2019-12-11 05:24 UTC, gtobio11 commented on src/containers/Meal/Meal.tsx
> +      ></Meal>
``` js
<Meal
        breakfast={mealList.breakfast}
        lunch={mealList.lunch}
        dinner={mealList.dinner} 
/>
```
이렇게 하면 더 간단해지지 않을까요 ?

2019-12-11 08:32 UTC, khg0712 requested changes

2019-12-11 08:32 UTC, khg0712 commented on src/containers/Meal/Meal.tsx
> +        breakfast={mealList.breakfast}
destructuring으로 더 간단하게 만들면 더 좋을 것 같습니다.
```
const {breakfast, lunch, dinner} = mealList;
```

2019-12-12 04:18 UTC, gimtommang11 commented on src/components/MealCard/MealCard.tsx
> +      <S.MealCardContainer>
열심히 생각해봤는데 제가 구상한 방법은 useEffect, useRef, useState를 사용해서 랜더링 된 후의 급식 값의 총 길이(MealInfoContainer)값을 받아와서 특정 값보다 작으면 일정한 간격을 줘서 처리하고, 크면 height와 space-between을 줘서 div를 빠져나가지 않도록 처리했습니다. 여기서 몇가지 의문점이 생겼는데
1. presentational component에서 useState ... 를 사용해도 될까요?
2. style부분에 중복되는 코드가 있는데 방법이 저것밖에 없을까요?
3. 이렇게 처리하면 랜더링될때 일시적으로 MealInfoContainer가 커지고 작아지는 현상이 발생하는데 어떻게 수정할 수 있을까요?
이것 말고 더 좋은 방법이 있을까요?ㅠㅠ 말해주시면 감사하겠습니다

2019-12-12 05:19 UTC, gimtommang11 commented on src/containers/Meal/Meal.tsx
> +        breakfast={mealList.breakfast}
오 그렇네용 수정하겠습니다

2019-12-12 10:04 UTC, gimtommang11 commented on src/containers/Meal/Meal.tsx
> +  const mealList = {
넹 당연하죵

2019-12-13 01:55 UTC, khg0712 requested changes

2019-12-13 01:55 UTC, khg0712 commented on src/components/MealInfo/style.ts
> +    justify-content: space-between
`justify-content`와 `margin-top`은 높이랑 상관없는 공통적인 속성이 아닌가요?

2019-12-13 01:55 UTC, khg0712 commented on src/components/MealCard/MealCard.tsx
> +      <S.MealCardContainer>
RE: 2. style부분에 중복되는 코드가 있는데 방법이 저것밖에 없을까요?

중복되는 코드라 함은 어떤 부분을 말씀하시는 건가요?

2019-12-13 01:55 UTC, khg0712 commented on src/components/MealInfo/style.ts
> +    justify-content: space-between
height도 저렇게 주지 말고 maxheight으로 주면 props쓸 필요가 없어보임

2019-12-13 01:55 UTC, khg0712 commented on src/components/MealInfo/style.ts
> +    justify-content: space-between
[링크](https://css-tricks.com/set-font-size-based-on-word-count/) 참고해서 급식 이름 길이에 따라서 다르게 fontsize 조정도 해보삼

2019-12-24 07:19 UTC, merged