Calender 퍼블리싱 완성
DSM-DMS/DMS-Front-V4 pull request #37
Opened 2020-03-17 18:48 UTC by gimtommang11

###  완성한 부분
**달력**과, 선택된 날에 맞는 학사일정을 보여주기 위해 **학사일정 표시란 퍼블리싱**을 진행하였습니다
### 유의점
아직 redux을 이용하지 않았습니다. 머지 된 후에, redux를 이용하여 깔끔하게 리팩토링 할 것 입니다.
또한 아직 선택된 날의 달이 몇월달인지 보여주는 디자인이 없어서 제가 임의로 넣었습니다.

2020-03-18 02:31 UTC, khg0712 commented
master에서 pull 받아라 conflict 난다 @gimtommang11

2020-03-18 02:38 UTC, leafcis commented on src/components/CalendarItem/CalendarItem.tsx
> +      onClick={(event: React.MouseEvent<HTMLElement>) => {
useCallback를 써보면 어떨까

2020-03-18 02:38 UTC, leafcis commented on src/components/Calendar/Calendar.tsx
> +          onClick={(event: React.MouseEvent<HTMLElement>) => {
onClick={getNextWeek} 로 바꾸면 어떰

2020-03-18 06:32 UTC, khg0712 requested changes

2020-03-18 06:32 UTC, khg0712 commented on src/components/Calendar/Calendar.tsx
> +          }}
```suggestion
          onClick={getLastWeek}
```

2020-03-18 06:32 UTC, khg0712 commented on src/containers/AcademicCalendar/AcademicCalendar.tsx
> +      <AcademicCalendar AcademicCalendarData={dummy.AcademicCalendar} />
fragment로 감싼 이유가 없어보여요

2020-03-18 15:28 UTC, gimtommang11 commented on src/components/Calendar/Calendar.tsx
> +          onClick={(event: React.MouseEvent<HTMLElement>) => {
그러는편이 더 깔끔하네요 수정하겟습니당

2020-03-18 15:28 UTC, gimtommang11 commented on src/components/Calendar/Calendar.tsx
> +          }}
감사합니다

2020-03-18 18:24 UTC, gimtommang11 commented on src/containers/AcademicCalendar/AcademicCalendar.tsx
> +      <AcademicCalendar AcademicCalendarData={dummy.AcademicCalendar} />
넵 수정하도록 하겠습니다

2020-03-19 11:39 UTC, gimtommang11 commented on src/containers/AcademicCalendar/AcademicCalendar.tsx
> +      <AcademicCalendar AcademicCalendarData={dummy.AcademicCalendar} />
넵 수정하였습니다

2020-03-19 11:41 UTC, gimtommang11 commented on src/components/CalendarItem/CalendarItem.tsx
> +      onClick={(event: React.MouseEvent<HTMLElement>) => {
오 useCallback을 사용하는것이 더 좋을것같네요 수정해보도록 하겟습니다

2020-03-23 15:32 UTC, merged