Modals 파일구조 변경, on-off 기능 추가
DSM-DMS/DMS-Front-V4 pull request #38
Opened 2020-03-24 18:28 UTC by gimtommang11

### 수정한 부분
기존에는 modals 디랙토리에 style.ts과 각 컴포넌트를 넣어서, **여러 컴포넌트가 한 style.ts** 을 사용하였습니다. 
이것이 좋지 않다고 판단하여, **재사용 가능한 컴포넌트들은 따로 분리**하고, SignIn,LogIn과 같은 컴포넌트들도 **각 디랙토리에 각각의 style.ts를 사용하도록 분리**하였습니다

### 추가한 부분
redux를 사용해서 ModalContainer 내부에서 modalType을 변경해, **클릭시 각 다른 모달을 보여주는 기능**과, **on-off 기능**을 추가하였습니다

### 조언을 구하는 부분
수정한 디랙토리 구조에서는, 전과 흡사하게 Modals디랙토리에 관련된 컴포넌트 디랙토리들이 모두 위치해 있습니다. 이 부분에 대해서 **Modals 디랙토리에서 꺼내야할지, 안에 위치시켜야할지 어떤 방법이 더 좋을지**에 대해 조언을 구하고자 합니다

2020-03-25 06:24 UTC, gtobio11 commented
일단 PR 단위가 너무 큽니다.

2020-03-25 06:30 UTC, wArrnp requested changes

2020-03-25 06:30 UTC, gtobio11 commented on src/components/Header/Header.tsx
> +        <S.HeaderLeftFont className="main">{sectionTitle}</S.HeaderLeftFont>>
마지막의 >가 두개 있는 것은 의도된 것인가요 ?

2020-03-25 06:33 UTC, gtobio11 commented
회사에서 짧게 본 것이라 자세하게 평은 못내려도 중복적인 css가 많아보입니다.

styled.css로 공통 코드를 변수 하나로 묶은 뒤 같은 기능을 반복하는 코드들에서 해당 변수를 사용하는 방법을 사용하는 것이 간결해보입니다.

그리고 GlobalStyle에서 GlobalColor ? 를 Import해서 사용하는 것은 제가 초반에 남겨둔 똥이라고 생각되는데 상태에 따른 공통적인 변화를 객체 하나로 묶어두어 한번에 관리하는 것에 대해서 좀 더 고민하여 충분히 도입해보아야 한다고 생각합니다.

화이팅.

2020-03-25 06:38 UTC, gtobio11 commented on src/modules/modal.ts
> +      return { ...state, isVisible: false };
```suggestion

      case SHOW:
      return { ...state, isVisible: true };
    case HIDE:
      return { ...state, isVisible: false };ible: false };
```

2020-03-25 06:50 UTC, wArrnp requested changes

2020-03-25 06:50 UTC, gtobio11 commented on src/modules/modal.ts
> +      return { ...state, isVisible: false };
```suggestion
    case TOGGLE:
        return { ...state, isVisible: action.payload.isVisible }
```
굳이 true false를 toggle하는 이벤트를 액션 두개로 나눌 필요가 있나 싶습니다. 
액션 dispatch 호출할 때 인자로 boolean 값을 넘기거나 `!isVisible` 이 부분에 대해서 고려해보는 것은 어떤가 싶네요.

2020-03-25 06:50 UTC, gtobio11 commented on src/components/Modals/Login/style.ts
> +  align-items: center;
이런 중앙 정렬 코드를 
```suggestion
const Centerize = styled.css`
    display: flex;
    justify-content: center;
    align-items: center;
`
export const SignInLinkWrapper = styled.div`
    {Centerize}
    ~~
`
```

이런식으로 재사용 하는 것이 좋아보입니다. 너무 많은 곳에서 중복적으로 쓰입니다.

그리고 flex를 너무 사랑하진 마세요.

2020-03-25 06:50 UTC, gtobio11 commented on src/containers/Header/Header.tsx
> +  };
useCallback으로 바꾸는건 어떨까요

2020-03-25 06:50 UTC, gtobio11 commented on src/containers/ModalWrapper/ModalWrapper.tsx
> +  };
역시 useCallback에 대해서 고민해주세요 ㅎㅎ

2020-03-25 13:02 UTC, gimtommang11 commented on src/components/Header/Header.tsx
> +        <S.HeaderLeftFont className="main">{sectionTitle}</S.HeaderLeftFont>>
이 부분은 
![image](https://user-images.githubusercontent.com/37663077/77534061-59b2ba80-6edb-11ea-8e52-1425a6040c7f.png)
여기의 ">" 를 나타내기 위해 있는것입니다

2020-03-25 13:33 UTC, gimtommang11 commented
> 일단 PR 단위가 너무 큽니다.

파일구조 변경과 on-off 기능 추가 이렇게 두 개로 나눠서 풀리퀘를 보내는것이 바람직할까요?

2020-03-25 13:35 UTC, gimtommang11 commented on src/modules/modal.ts
> +      return { ...state, isVisible: false };
넵 그렇네요 하나의 엑션으로 관리하는쪽으로 수정하겟습니다

2020-03-25 16:35 UTC, gimtommang11 commented on src/components/Modals/Login/style.ts
> +  align-items: center;
넵 저런방법이 있는지는 몰랐네요 :O 수정하도록 하겠습니다 :)

2020-03-26 09:58 UTC, wArrnp requested changes

2020-03-26 09:58 UTC, gtobio11 commented on src/components/Modals/Login/style.ts
> +`;
세로로만 정렬하려는 의도라면 verticalAlignCenter 이와 같이 세로로만 정렬한다는 것을 명시해주면 어떨까요 ?

그리고 정렬같은 경우 코드 전반적인 곳에서 모두 사용 될테니 GlobalState에 미리 정의하는 것이 좋을 것 같습니다 ㅎㅎ

2020-03-26 11:38 UTC, gimtommang11 commented on src/components/Modals/Login/style.ts
> +`;
넵 그것도 좋겠네요 해보겠습니다 :)

2020-03-26 11:39 UTC, gimtommang11 commented on src/containers/Header/Header.tsx
> +  };
수정하였습니다 :)

2020-03-28 15:00 UTC, gimtommang11 commented on src/components/Modals/Login/style.ts
> +`;
이삭이와 예기를 해봤는데 GlogbalStyle에 따로 빼는 부분은 전체적인 개발이 끝나고 고쳐가는 부분에서 추가하는게 좋을것같아서 추후에 변경하도록 하겠습니당

2020-03-30 06:25 UTC, gtobio11 commented on src/components/Header/Header.tsx
> +        <S.HeaderLeftFont className="main">{sectionTitle}</S.HeaderLeftFont>>
엔터로 구분해주세요 ! 헷갈립니당 ㅎㅎ

2020-03-30 12:37 UTC, merged