마이페이지 신청상태 부분 CSS 완성
DSM-DMS/DMS-Front-V4 pull request #5
Opened 2019-08-15 09:43 UTC by gtobio11

2019-08-23 00:37 UTC, khg0712 requested changes

2019-08-23 00:37 UTC, khg0712 commented on src/components/Chatting/Chatting.tsx
> +  return <div>2</div>;
2의 의미가 뭔가요?

2019-08-23 00:37 UTC, khg0712 commented on src/components/MypageStatus/MypageStatus.tsx
> +        상점 : 18점&nbsp;&nbsp;&nbsp;벌점 : 1점
css를 통해서 공백을 주는 게 더 낫지 않을까요?

2019-08-23 03:00 UTC, gtobio11 commented on src/components/Chatting/Chatting.tsx
> +  return <div>2</div>;
테스팅용 문구입니다. 무시하셔도 됩니다.

2019-08-23 03:01 UTC, gtobio11 commented on src/components/MypageStatus/MypageStatus.tsx
> +        상점 : 18점&nbsp;&nbsp;&nbsp;벌점 : 1점
css를 주기 위해서 상점과 벌점에 각각 태그를 지정해줘야하는데, 그럴경우 html depth 가 더 깊어지게 되는데 그럴 필요성이 있을까 싶어 위와 같이 했습니다.

2019-08-23 05:56 UTC, khg0712 commented on src/components/MypageStatus/MypageStatus.tsx
> +        상점 : 18점&nbsp;&nbsp;&nbsp;벌점 : 1점
저렇게 하면 반응형 ui를 작성하기 힘들어진다고 생각합니다

2019-08-23 06:51 UTC, leafcis reviewed
확인했습니다

2019-08-23 07:04 UTC, gtobio11 commented on src/components/MypageStatus/MypageStatus.tsx
> +        상점 : 18점&nbsp;&nbsp;&nbsp;벌점 : 1점
흠 오키 수정하겠슴다

2019-08-23 09:01 UTC, gtobio11 commented on src/components/MypageStatus/MypageStatus.tsx
> +        상점 : 18점&nbsp;&nbsp;&nbsp;벌점 : 1점
수정했습니당 확인 부탁드려여

2019-08-25 13:09 UTC, khg0712 approved these changes
Good

2019-08-25 13:47 UTC, merged