[CREATE] <Notice Tags> Notice 태그들 UI 완성
DSM-DMS/DMS-Front-V4 pull request #6
Opened 2019-08-23 09:02 UTC by gtobio11

2019-08-25 14:12 UTC, khg0712 commented on src/components/NoticeTagItem/NoticeTagItem.tsx
> +  nowClickedTag: string;
selectedTag로 바꿔주셈

2019-08-25 14:12 UTC, khg0712 commented on src/components/NoticeTagItem/NoticeTagItem.tsx
> +  onClickTag: (tagTitle: string) => void;
따로 tagId를 주면 안될까요?

2019-08-25 14:12 UTC, khg0712 commented on src/components/NoticeTagItem/NoticeTagItem.tsx
> +      isClick={nowClickedTag === tagTitle}
isSelected가 더 좋은듯합니다

2019-08-25 14:12 UTC, khg0712 commented on src/components/NoticeTagsList/NoticeTagsList.tsx
> +  return <S.NoticeTagsListWrapper>{NoticeTagItems}</S.NoticeTagsListWrapper>;
this.props.children을 쓰는 건 어떤가요

2019-08-27 13:40 UTC, khg0712 requested changes

2019-08-27 13:40 UTC, khg0712 commented on src/components/NoticeTagItem/NoticeTagItem.tsx
> +      {tagId}
tagId 보다는 tagTitle이 더 어울리는 이름인 것 같아요

2019-08-27 14:51 UTC, gtobio11 commented on src/components/NoticeTagItem/NoticeTagItem.tsx
> +  nowClickedTag: string;
done

2019-08-27 14:52 UTC, gtobio11 commented on src/components/NoticeTagItem/NoticeTagItem.tsx
> +  onClickTag: (tagTitle: string) => void;
done

2019-08-27 14:52 UTC, gtobio11 commented on src/components/NoticeTagItem/NoticeTagItem.tsx
> +      isClick={nowClickedTag === tagTitle}
done

2019-08-27 14:52 UTC, gtobio11 commented on src/components/NoticeTagsList/NoticeTagsList.tsx
> +  return <S.NoticeTagsListWrapper>{NoticeTagItems}</S.NoticeTagsListWrapper>;
done

2019-08-27 14:52 UTC, gtobio11 commented on src/components/NoticeTagItem/NoticeTagItem.tsx
> +      {tagId}
done

2019-08-31 13:43 UTC, khg0712 requested changes

2019-08-31 13:43 UTC, khg0712 commented on src/components/NoticeTagItem/NoticeTagItem.tsx
> +  onClickTag: (tagId: String) => void;
string이 맞는 표현 같습니다.

2019-08-31 13:44 UTC, khg0712 approved these changes

2019-08-31 13:45 UTC, leafcis approved these changes

2019-08-31 14:01 UTC, merged